package org.xmlcml.cml.units;

import nu.xom.Element;
import nu.xom.Node;

/**
 * user-modifiable class supporting dimension. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class JumboDimension extends Element {

	private String dimensionBasis;
	private String id;
	private String name;
	private double power;
	private String preserve;
	
    /**
     * constructor.
     */
    public JumboDimension() {
    	super("dimension");
    }

    /**
     * constructor.
     *
     * @param old
     */
    public JumboDimension(JumboDimension old) {
        super(old.getName());
    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new JumboDimension(this);

    }


    /**
     * returns super.getPower(). enforces default value of 1.0 if attribute
     * missing.
     *
     * @return the power (default = 1.0)
     */
    public double getPower() {
    	return power;
    }

	public String getDimensionBasis() {
		return dimensionBasis;
	}

	public void setDimensionBasis(String dimensionBasis) {
		this.dimensionBasis = dimensionBasis;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPreserve() {
		return preserve;
	}

	public void setPreserve(String preserve) {
		this.preserve = preserve;
	}

	public void setPower(double power) {
		this.power = power;
	}
}
